version: "3.8"

services:
  code-server:
    image: ghcr.io/natankeddem/docker-code-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKERGID=999
      - TZ=Etc/UTC
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD= #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      # - /path/to/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - 8443:8443
